# Data Preparation

In [2]:
import pandas as pd 
import numpy as np

### Loading data in pandas

In [5]:

df=pd.read_csv("project_eq_raw.csv")

In [6]:
df.shape

(119189, 26)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119189 entries, 0 to 119188
Data columns (total 26 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         119189 non-null  str
 1   time       119189 non-null  str
 2   updated    119189 non-null  str
 3   latitude   119189 non-null  float64
 4   longitude  119189 non-null  float64
 5   depth_km   119189 non-null  float64
 6   mag        119189 non-null  float64
 7   magType    119189 non-null  str
 8   place      119189 non-null  str
 9   status     119189 non-null  str
 10  tsunami    119189 non-null  int64
 11  alert      4872 non-null    str
 12  felt       18131 non-null   float64
 13  cdi        18131 non-null   float64
 14  mmi        10541 non-null   float64
 15  sig        119189 non-null  int64
 16  net        119189 non-null  str
 17  code       119189 non-null  str
 18  ids        119189 non-null  str
 19  sources    119189 non-null  str
 20  types      119189 non-null  str
 21  nst        91427 non-null   float64
 22  dmin       115211 non-null  float64
 23  rms        119170 non-null  float64
 24  gap        116165 non-null  float64
 25  type       119189 non-null  str
dtypes: float64(11), int64(2), str(13)
memory usage: 23.6 MB

In [8]:
df.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'alert', 'felt', 'cdi', 'mmi',
       'sig', 'net', 'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms',
       'gap', 'type'],
      dtype='str')

### Converting time into datetime format

In [9]:

df["time"]=pd.to_datetime(df["time"])

### Converting updated into datetime format

In [10]:

df["updated"]=pd.to_datetime(df["updated"])

## Cleaning text fields

### Extract country using regex

In [13]:

df["country"]=df['place'].str.extract(r',\s*([^,]+)$')

In [14]:
df[['place','country']]

,place,country
0,"29 km SW of Villa Basilio Nievas, Argentina",Argentina
1,Fiji region,NaN
2,"103 km SW of Basco, Philippines",Philippines
3,"114 km N of M?n?b, Iran",Iran
4,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",Svalbard and Jan Mayen
...,...,...
119184,"4 km WSW of Caldera, Panama",Panama
119185,"58 km SSW of Adak, Alaska",Alaska
119186,"22 km SE of Punta Cana, Dominican Republic",Dominican Republic
119187,"3 km E of Nelson Lagoon, Alaska",Alaska
119188,"292 km WNW of Houma, Tonga",Tonga

In [15]:
df.head()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,code,ids,sources,types,nst,dmin,rms,gap,type,country
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,6000ddi8,",us6000ddi8,",",us,",",dyfi,moment-tensor,origin,phase-data,",NaN,0.294,0.82,42.0,earthquake,Argentina
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,mb,Fiji region,reviewed,...,6000dev6,",us6000dev6,",",us,",",origin,phase-data,",NaN,1.471,0.29,64.0,earthquake,NaN
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,mb,"103 km SW of Basco, Philippines",reviewed,...,6000dev5,",us6000dev5,",",us,",",origin,phase-data,",NaN,3.057,0.69,106.0,earthquake,Philippines
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,mb,"114 km N of M?n?b, Iran",reviewed,...,6000ddhs,",us6000ddhs,",",us,",",origin,phase-data,",NaN,3.330,0.61,71.0,earthquake,Iran
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,6000dev4,",us6000dev4,",",us,",",origin,phase-data,",NaN,6.023,0.50,65.0,earthquake,Svalbard and Jan Mayen

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119189 entries, 0 to 119188
Data columns (total 27 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         119189 non-null  str
 1   time       119189 non-null  datetime64[us]
 2   updated    119189 non-null  datetime64[us]
 3   latitude   119189 non-null  float64
 4   longitude  119189 non-null  float64
 5   depth_km   119189 non-null  float64
 6   mag        119189 non-null  float64
 7   magType    119189 non-null  str
 8   place      119189 non-null  str
 9   status     119189 non-null  str
 10  tsunami    119189 non-null  int64
 11  alert      4872 non-null    str
 12  felt       18131 non-null   float64
 13  cdi        18131 non-null   float64
 14  mmi        10541 non-null   float64
 15  sig        119189 non-null  int64
 16  net        119189 non-null  str
 17  code       119189 non-null  str
 18  ids        119189 non-null  str
 19  sources    119189 non-null  str
 20  types      119189 non-null  str
 21  nst        91427 non-null   float64
 22  dmin       115211 non-null  float64
 23  rms        119170 non-null  float64
 24  gap        116165 non-null  float64
 25  type       119189 non-null  str
 26  country    97650 non-null   str
dtypes: datetime64[us](2), float64(11), int64(2), str(12)
memory usage: 24.6 MB

In [17]:
df.isnull()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,code,ids,sources,types,nst,dmin,rms,gap,type,country
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119184,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
119185,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
119186,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
119187,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
119188,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119189 entries, 0 to 119188
Data columns (total 27 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         119189 non-null  str
 1   time       119189 non-null  datetime64[us]
 2   updated    119189 non-null  datetime64[us]
 3   latitude   119189 non-null  float64
 4   longitude  119189 non-null  float64
 5   depth_km   119189 non-null  float64
 6   mag        119189 non-null  float64
 7   magType    119189 non-null  str
 8   place      119189 non-null  str
 9   status     119189 non-null  str
 10  tsunami    119189 non-null  int64
 11  alert      4872 non-null    str
 12  felt       18131 non-null   float64
 13  cdi        18131 non-null   float64
 14  mmi        10541 non-null   float64
 15  sig        119189 non-null  int64
 16  net        119189 non-null  str
 17  code       119189 non-null  str
 18  ids        119189 non-null  str
 19  sources    119189 non-null  str
 20  types      119189 non-null  str
 21  nst        91427 non-null   float64
 22  dmin       115211 non-null  float64
 23  rms        119170 non-null  float64
 24  gap        116165 non-null  float64
 25  type       119189 non-null  str
 26  country    97650 non-null   str
dtypes: datetime64[us](2), float64(11), int64(2), str(12)
memory usage: 24.6 MB

In [20]:
df.isnull()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,code,ids,sources,types,nst,dmin,rms,gap,type,country
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119184,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
119185,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
119186,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
119187,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
119188,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [21]:
df.select_dtypes(include='object').columns.tolist()

C:\Users\varsh\AppData\Local\Temp\ipykernel_13556\3152244773.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object').columns.tolist()

['id',
 'magType',
 'place',
 'status',
 'alert',
 'net',
 'code',
 'ids',
 'sources',
 'types',
 'type',
 'country']

### Removing extra space and lowercase in string field

In [24]:

str_field=['id','magType','place','status','net','types','ids','sources','type','alert']

In [25]:

for i in str_field:
    df[i]=df[i].str.strip().str.lower()

In [26]:
df['country'].str.title()

0                      Argentina
1                            NaN
2                    Philippines
3                           Iran
4         Svalbard And Jan Mayen
                   ...
119184                    Panama
119185                    Alaska
119186        Dominican Republic
119187                    Alaska
119188                     Tonga
Name: country, Length: 119189, dtype: str

### Removing unwanted commas from  and types

In [27]:
comma_columns = ["ids","types","sources"]

In [28]:
for i in comma_columns:
    df[i]=df[i].str.replace(",","")

In [29]:
df[comma_columns].head()

          ids                              types sources
0  us6000ddi8  dyfimoment-tensororiginphase-data      us
1  us6000dev6                   originphase-data      us
2  us6000dev5                   originphase-data      us
3  us6000ddhs                   originphase-data      us
4  us6000dev4                   originphase-data      us

In [30]:
df['types'].nunique()

583

In [33]:
df.duplicated("id").sum()

np.int64(0)

## Clean Numeric field

### Filling missing values with 0

In [35]:

df=df.fillna(0)

In [36]:
df.isnull()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,code,ids,sources,types,nst,dmin,rms,gap,type,country
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119184,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
119185,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
119186,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
119187,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
119188,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Add Derived Columns

### Adding new columns based on time

In [37]:

df["year"]=df['time'].dt.year
df["month"]=df['time'].dt.month
df["day"]=df['time'].dt.day
df["day-of_week"]=df["time"].dt.day_of_week

In [38]:
print(df)

                   id                    time                 updated  \
0          us6000ddi8 2021-01-31 23:20:49.923 2021-04-16 19:02:44.040
1          us6000dev6 2021-01-31 23:08:17.161 2021-04-16 19:03:47.040
2          us6000dev5 2021-01-31 22:54:19.760 2021-04-16 19:03:47.040
3          us6000ddhs 2021-01-31 22:06:00.832 2021-04-16 19:02:43.040
4          us6000dev4 2021-01-31 21:51:14.016 2021-04-16 19:03:46.040
...               ...                     ...                     ...
119184     us7000tdbz 2026-09-01 04:50:45.457 2026-09-01 20:23:31.864
119185  aka2026rhblzv 2026-09-01 03:04:24.961 2026-09-01 16:13:24.871
119186     pr71530493 2026-09-01 03:03:51.600 2026-09-01 09:34:39.270
119187     us7000td94 2026-09-01 02:22:48.557 2026-09-01 16:08:36.998
119188     us7000td8u 2026-09-01 01:29:10.774 2026-09-01 01:44:48.040

        latitude  longitude  depth_km   mag magType  \
0       -31.7493   -68.9337    17.270  4.70     mwr
1       -15.4902  -177.2052   426.710  4.10      mb
2        19.7529   121.3159    46.730  4.70      mb
3        28.1524    57.2570    10.000  4.90      mb
4        71.3212    -3.7578    10.000  4.00      mb
...          ...        ...       ...   ...     ...
119184    8.6353   -82.4204    10.000  3.60      ml
119185   51.4140  -177.0380    40.200  3.00      ml
119186   18.4445   -68.2475    93.890  3.42      md
119187   55.9965  -161.1496   192.579  3.30      ml
119188  -20.4066  -177.9940   533.035  4.80      mb

                                                    place    status  ...  \
0             29 km sw of villa basilio nievas, argentina  reviewed  ...
1                                             fiji region  reviewed  ...
2                         103 km sw of basco, philippines  reviewed  ...
3                                 114 km n of m?n?b, iran  reviewed  ...
4       184 km ene of olonkinbyen, svalbard and jan mayen  reviewed  ...
...                                                   ...       ...  ...
119184                        4 km wsw of caldera, panama  reviewed  ...
119185                          58 km ssw of adak, alaska  reviewed  ...
119186         22 km se of punta cana, dominican republic  reviewed  ...
119187                    3 km e of nelson lagoon, alaska  reviewed  ...
119188                         292 km wnw of houma, tonga  reviewed  ...

         nst    dmin   rms    gap        type                 country  year  \
0        0.0  0.2940  0.82   42.0  earthquake               Argentina  2021
1        0.0  1.4710  0.29   64.0  earthquake                       0  2021
2        0.0  3.0570  0.69  106.0  earthquake             Philippines  2021
3        0.0  3.3300  0.61   71.0  earthquake                    Iran  2021
4        0.0  6.0230  0.50   65.0  earthquake  Svalbard and Jan Mayen  2021
...      ...     ...   ...    ...         ...                     ...   ...
119184   6.0  1.0260  0.38  225.0  earthquake                  Panama  2026
119185  26.0  0.4000  0.50  213.0  earthquake                  Alaska  2026
119186  13.0  0.1445  0.41  176.0  earthquake      Dominican Republic  2026
119187  16.0  0.6760  0.61  132.0  earthquake                  Alaska  2026
119188  69.0  4.5810  1.00   63.0  earthquake                   Tonga  2026

       month day day-of_week
0          1  31           6
1          1  31           6
2          1  31           6
3          1  31           6
4          1  31           6
...      ...  ..         ...
119184     9   1           1
119185     9   1           1
119186     9   1           1
119187     9   1           1
119188     9   1           1

[119189 rows x 31 columns]

In [39]:
df.head()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,nst,dmin,rms,gap,type,country,year,month,day,day-of_week
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,mwr,"29 km sw of villa basilio nievas, argentina",reviewed,...,0.0,0.294,0.82,42.0,earthquake,Argentina,2021,1,31,6
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,mb,fiji region,reviewed,...,0.0,1.471,0.29,64.0,earthquake,0,2021,1,31,6
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,mb,"103 km sw of basco, philippines",reviewed,...,0.0,3.057,0.69,106.0,earthquake,Philippines,2021,1,31,6
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,mb,"114 km n of m?n?b, iran",reviewed,...,0.0,3.330,0.61,71.0,earthquake,Iran,2021,1,31,6
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,mb,"184 km ene of olonkinbyen, svalbard and jan mayen",reviewed,...,0.0,6.023,0.50,65.0,earthquake,Svalbard and Jan Mayen,2021,1,31,6

In [41]:
df.head(10)

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,nst,dmin,rms,gap,type,country,year,month,day,day-of_week
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.70,mwr,"29 km sw of villa basilio nievas, argentina",reviewed,...,0.0,0.2940,0.82,42.0,earthquake,Argentina,2021,1,31,6
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.10,mb,fiji region,reviewed,...,0.0,1.4710,0.29,64.0,earthquake,0,2021,1,31,6
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.70,mb,"103 km sw of basco, philippines",reviewed,...,0.0,3.0570,0.69,106.0,earthquake,Philippines,2021,1,31,6
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.90,mb,"114 km n of m?n?b, iran",reviewed,...,0.0,3.3300,0.61,71.0,earthquake,Iran,2021,1,31,6
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.00,mb,"184 km ene of olonkinbyen, svalbard and jan mayen",reviewed,...,0.0,6.0230,0.50,65.0,earthquake,Svalbard and Jan Mayen,2021,1,31,6
5,pr2021031019,2021-01-31 21:34:54.690,2021-04-16 19:02:43.040,18.9996,-65.4121,46.00,3.55,md,"76 km nne of luquillo, puerto rico",reviewed,...,11.0,0.9132,0.31,305.0,earthquake,Puerto Rico,2021,1,31,6
6,pr2021031018,2021-01-31 21:26:30.180,2021-01-31 21:52:15.880,19.0250,-65.4221,30.00,3.27,md,"78 km nne of luquillo, puerto rico",reviewed,...,9.0,0.9368,0.37,305.0,earthquake,Puerto Rico,2021,1,31,6
7,pr2021031020,2021-01-31 21:14:31.020,2021-04-16 19:02:43.040,19.0436,-65.3590,28.00,3.48,md,"82 km n of culebra, puerto rico",reviewed,...,14.0,0.9659,0.37,309.0,earthquake,Puerto Rico,2021,1,31,6
8,us6000dev3,2021-01-31 20:57:55.804,2021-04-16 19:03:46.040,5.6376,126.7150,18.68,4.30,mb,"99 km se of pondaguitan, philippines",reviewed,...,0.0,1.8160,0.49,139.0,earthquake,Philippines,2021,1,31,6
9,us6000dev2,2021-01-31 20:54:42.248,2021-04-16 19:03:46.040,5.8436,126.5404,75.53,4.20,mb,"69 km se of pondaguitan, philippines",reviewed,...,0.0,5.1050,0.58,196.0,earthquake,Philippines,2021,1,31,6

In [49]:
df["alert"].value_counts()

alert
0         114317
green       4677
yellow       142
red           28
orange        25
Name: count, dtype: int64

In [50]:
df['felt']

0         12.0
1          0.0
2          0.0
3          0.0
4          0.0
          ...
119184     6.0
119185     0.0
119186     0.0
119187     0.0
119188     0.0
Name: felt, Length: 119189, dtype: float64

In [42]:
df.columns[(df==0).all()]

Index([], dtype='str')

In [43]:
zero_columns=['magError', 'depthError', 'magNst', 'locationSource', 'magSource']

In [45]:
df.head()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,nst,dmin,rms,gap,type,country,year,month,day,day-of_week
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,mwr,"29 km sw of villa basilio nievas, argentina",reviewed,...,0.0,0.294,0.82,42.0,earthquake,Argentina,2021,1,31,6
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,mb,fiji region,reviewed,...,0.0,1.471,0.29,64.0,earthquake,0,2021,1,31,6
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,mb,"103 km sw of basco, philippines",reviewed,...,0.0,3.057,0.69,106.0,earthquake,Philippines,2021,1,31,6
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,mb,"114 km n of m?n?b, iran",reviewed,...,0.0,3.330,0.61,71.0,earthquake,Iran,2021,1,31,6
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,mb,"184 km ene of olonkinbyen, svalbard and jan mayen",reviewed,...,0.0,6.023,0.50,65.0,earthquake,Svalbard and Jan Mayen,2021,1,31,6

### download csv file

In [51]:
df.to_csv("project_eq_clean.csv", index= False)